### ISSUE TITLE
tls.certResolver can have an empty value

### ISSUE THREAD

**Issue by spatterIight** [mother-of-all-self-hosting/ansible-role-vaultwarden#3]
In certain deployment configurations `tls.certResolver` can have an empty value, resulting in broken Traefik routing to the container

For some time I have bypassed this issue with an Ansible post task:

```yaml
 tasks:
    - name: Remove faulty Vaultwarden label
      ansible.builtin.lineinfile:
        path: /smirnoff/mash/vaultwarden/labels
        search_string: "traefik.http.routers.mash-vaultwarden.tls.certResolver="
        state: absent
      tags: always
```

The fix is a J2 if-else that other roles have, will be putting in a PR for it soon.
